server:
  port: 8082

spring:
  cloud:
    gateway:
      routes:
        - id: user-center
          uri: http://127.0.0.1:8080/users
          predicates:
            - Path=/users/**
        - id: email-service
          uri: lb://email-service
          predicates:
            - Path=/emails/**

  application:
    name: gateway-server

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka